package io.podcentral.rss;

import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.podcentral.config.TableConstants;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

@NoArgsConstructor
@RequiredArgsConstructor
@DynamoDBTable(tableName = TableConstants.Channel.TABLE_NAME)
@Data
public class Channel {
  @NonNull
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  private String title;
  private String description;
  private String link;
  private Date pubDate;
  private Date lastBuildDate;
  private String language;
  private String copyright;
  private Integer ttl;
  @XmlPath("itunes:image/@href")
  private String imageUrl;
  @XmlElement(name = "category")
  private String rssCategory;
  @XmlPath("itunes:category/@text")
  private String itunesCategory;
  @XmlElement(name = "explicit", namespace = XmlNs.ITUNES)
  private Boolean explicit;
  @DynamoDBIgnore
  @XmlElement(name = "item")
  private List<Item> items;
}
