package io.podcentral.rss;

import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.eclipse.persistence.oxm.annotations.XmlPath;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import io.podcentral.xml.CsvAdapter;
import lombok.Data;

@DynamoDBTable(tableName = "Item")
@Data
public class Item {
  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  private String id;
  @DynamoDBIndexHashKey(globalSecondaryIndexName = "itemsByChannel")
  @DynamoDBAttribute
  private String channelId;
  @DynamoDBAttribute
  private String title;
  @DynamoDBAttribute
  private String link;
  @DynamoDBAttribute
  @XmlPath("itunes:image/@href")
  private String imageUrl;
  @DynamoDBAttribute
  private String description;
  @DynamoDBRangeKey
  @DynamoDBAttribute
  private Date pubDate;
  @DynamoDBAttribute
  @XmlPath("media:content[@medium='audio']/@url")
  private List<String> mediaUrls;
  @DynamoDBAttribute
  @XmlPath("media:content[@medium='image']/@url")
  private List<String> imageUrls;
  @DynamoDBAttribute
  @XmlJavaTypeAdapter(CsvAdapter.class)
  @XmlElement(namespace = XmlNs.MEDIA)
  private List<String> keywords;
}
